version: '3.8'

services:
  web:
    build: .
    container_name: php-apache
    ports:
      - "8855:80"
    depends_on:
      - mysql
      - opensearch
    environment:
      DB_HOST: mysql
      DB_NAME: magento
      DB_USER: root
      DB_PASSWORD: root_password
      OPENSEARCH_HOST: opensearch
      OPENSEARCH_PORT: 9200
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: magento
      MYSQL_USER: magento_user
      MYSQL_PASSWORD: magento_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  opensearch:
    image: opensearchproject/opensearch:2.9.0
    container_name: opensearch
    environment:
      bootstrap.memory_lock: 'true'
      discovery.type: 'single-node'
      OPENSEARCH_DISCOVERY_TYPE: 'single-node'
      OPENSEARCH_HTTP_SSL_ENABLED: 'true'
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: '@cyb86hmWP6Hx7'
      OPENSEARCH_NODE_NAME: 'opensearch-node'
      OPENSEARCH_PA_PORT: 9600
      OPENSEARCH_PORT: 9200
      plugins.security.disabled: 'true'
      plugins.security.ssl.http.enabled: 'true'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - app-network

volumes:
  opensearch-data:
  mysql-data:

networks:
  app-network:
